# Generated by Django 5.2.6 on 2026-04-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_alter_articulo_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='canal_ataque',
            field=models.CharField(default='indefinido', max_length=30),
        ),
        migrations.AddField(
            model_name='articulo',
            name='ejemplos_ataque',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='articulo',
            name='objetivo_ataque',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='articulo',
            name='origen_ataque',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='articulo',
            name='proceso_ataque',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='articulo',
            name='recomendaciones',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='articulo',
            name='secuencia_ataque',
            field=models.TextField(default=''),
        ),
    ]
