# Generated by Django 5.2.6 on 2026-09-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_articulo_canal_ataque_articulo_ejemplos_ataque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='respuesta_ia',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
