# Generated by Django 5.2.6 on 2026-09-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0004_articulo_respuesta_ia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='canal_ataque',
            field=models.TextField(default=''),
        ),
    ]
