# Generated by Django 5.2.6 on 2026-08-14 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0002_respuestaejercicio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('duracion', models.CharField(default='5 min', max_length=50)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('contenido_titulo', models.CharField(blank=True, max_length=255)),
                ('activa', models.BooleanField(default=True)),
                ('bloqueada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'leccion_capacitacion',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SeccionLeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encabezado', models.CharField(max_length=255)),
                ('texto', models.TextField(blank=True, default='')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='capacitaciones.leccion')),
            ],
            options={
                'db_table': 'seccion_leccion',
                'ordering': ['leccion', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='ProgresoCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completada', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_completacion', models.DateTimeField(blank=True, null=True)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='capacitaciones.leccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progreso_capacitaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'progreso_capacitacion',
                'ordering': ['-fecha_completacion', '-fecha_inicio'],
                'unique_together': {('usuario', 'leccion')},
            },
        ),
        migrations.CreateModel(
            name='ItemListaSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_lista', to='capacitaciones.seccionleccion')),
            ],
            options={
                'db_table': 'item_lista_seccion',
                'ordering': ['seccion', 'orden'],
            },
        ),
    ]
