# Generated by Django 5.2.6 on 2026-09-09 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0003_create_training_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestaejercicio',
            name='ejercicio',
        ),
        migrations.RemoveField(
            model_name='opcionejercicio',
            name='ejercicio',
        ),
        migrations.RemoveField(
            model_name='respuestaejercicio',
            name='opcion_seleccionada',
        ),
        migrations.RemoveField(
            model_name='respuestaejercicio',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Ejercicio',
        ),
        migrations.DeleteModel(
            name='OpcionEjercicio',
        ),
        migrations.DeleteModel(
            name='RespuestaEjercicio',
        ),
    ]
