# Generated by Django 5.2.6 on 2026-03-05 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='simulacion',
            table='simulacion',
        ),
    ]
