# Generated by Django 5.2.6 on 2026-04-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulaciones', '0002_alter_simulacion_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacion',
            name='resumen_justificacion',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='simulacion_texto',
            field=models.TextField(default=''),
        ),
    ]
