# Generated by Django 5.2.6 on 2026-04-10 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_alter_articulo_table'),
        ('simulaciones', '0003_simulacion_resumen_justificacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='simulacion',
            constraint=models.UniqueConstraint(fields=('articulo',), name='unique_simulacion_por_articulo'),
        ),
    ]
