# Generated by Django 5.2.6 on 2026-04-11 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_articulo_canal_ataque_articulo_ejemplos_ataque_and_more'),
        ('simulaciones', '0004_simulacion_unique_simulacion_por_articulo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simulacion',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.RemoveConstraint(
            model_name='simulacion',
            name='unique_simulacion_por_articulo',
        ),
        migrations.RenameField(
            model_name='simulacion',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='simulacion',
            name='attachments',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='dominio_objetivo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='enlace_senuelo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='entidad_objetivo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='es_mostrada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='es_phishing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='fecha_respuesta',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='sender_email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='subject',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='tipo_generacion',
            field=models.CharField(choices=[('inicial', 'Inicial'), ('regenerado', 'Regenerado')], default='inicial', max_length=20),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='tipo_mensaje',
            field=models.CharField(default='correo', max_length=20),
        ),
        migrations.AlterField(
            model_name='simulacion',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulaciones_generadas', to='articulos.articulo'),
        ),
        migrations.AlterField(
            model_name='simulacion',
            name='feedback',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='simulacion',
            name='resultado',
            field=models.CharField(choices=[('correcto', 'Correcto'), ('incorrecto', 'Incorrecto'), ('sin-responder', 'Sin responder')], default='sin-responder', max_length=20),
        ),
        migrations.AlterField(
            model_name='simulacion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulaciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
