# Generated by Django on 2026-07-15

from django.db import migrations, models
from django.db import connection


def backfill_id_iainteraction(apps, schema_editor):
    AIInteraction = apps.get_model('simulaciones', 'AIInteraction')
    # Assign sequential values starting at 1 ordered by PK to existing rows
    seq = 1
    # Use iterator to avoid loading all rows in memory
    for obj in AIInteraction.objects.all().order_by('id'):
        AIInteraction.objects.filter(pk=obj.pk).update(id_iainteraction=seq)
        seq += 1


def create_postgres_sequence(apps, schema_editor):
    # If using Postgres, create a sequence and set default to nextval(seq)
    vendor = connection.vendor
    if vendor != 'postgresql':
        return

    with connection.cursor() as cursor:
        # Create sequence if not exists
        cursor.execute("CREATE SEQUENCE IF NOT EXISTS ai_interaction_id_iainteraction_seq;")
        # Set values for rows without id_iainteraction using sequence
        # Ensure sequence is initialized to at least 1 to avoid invalid setval(0)
        cursor.execute("SELECT setval('ai_interaction_id_iainteraction_seq', COALESCE((SELECT MAX(id_iainteraction) FROM ai_interaction), 1));")
        # Alter column default to nextval
        cursor.execute("ALTER TABLE ai_interaction ALTER COLUMN id_iainteraction SET DEFAULT nextval('ai_interaction_id_iainteraction_seq');")


class Migration(migrations.Migration):

    dependencies = [
        ('simulaciones', '0006_create_aiinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinteraction',
            name='id_iainteraction',
            field=models.BigIntegerField(editable=False, null=True, unique=True),
        ),
        migrations.RunPython(backfill_id_iainteraction, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(create_postgres_sequence, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='aiinteraction',
            name='id_iainteraction',
            field=models.BigIntegerField(editable=False, null=False, unique=True),
        ),
    ]
