# Generated by Django 5.2.6 on 2026-09-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulaciones', '0009_respuestasimulacion_delete_progresosimulacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacion',
            name='nombre_contacto',
            field=models.CharField(default='', help_text='Para WhatsApp/SMS: nombre del contacto que envía', max_length=255),
        ),
    ]
